[build]
dockerfilePath = "Dockerfile.dev"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 600
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[ports]]
port = 5000
protocol = "http"
